#!/usr/bin/env bash
# TEA HOUSE — CSS build
#
# Flattens css/main.css's @import graph into a single stylesheet, strips
# comments, and reports the size delta. @import is serialised by the browser,
# so shipping the flattened file is what keeps LCP inside budget.
#
# Usage:  bash tools/build-css.sh [outfile]      (default: dist/main.css)
set -euo pipefail

cd "$(dirname "$0")/.."
OUT="${1:-dist/main.css}"
mkdir -p "$(dirname "$OUT")"

# Order is explicit so a glob reordering can never change cascade outcome.
SHEETS=(
  css/variables.css
  css/base.css
  css/components/buttons.css
  css/components/header.css
  css/components/hero.css
  css/components/cards.css
  css/components/accordion.css
  css/components/modal.css
  css/components/carousel.css
  css/components/timeline.css
  css/components/sections.css
  css/components/footer.css
)

TOTAL=0
for s in "${SHEETS[@]}"; do
  [ -f "$s" ] || { echo "missing sheet: $s" >&2; exit 1; }
  bytes=$(stat -c%s "$s"); TOTAL=$((TOTAL + bytes))
done

{
  printf '/* TEA HOUSE — generated by tools/build-css.sh. Do not edit. */\n'
  for s in "${SHEETS[@]}"; do
    printf '\n/* ==== %s ==== */\n' "$s"
    cat "$s"
  done
} > "$OUT"

MIN_OUT="${OUT%.css}.min.css"
if npx --yes clean-css-cli@5 -O1 "$OUT" -o "$MIN_OUT" >/dev/null 2>&1 && [ -s "$MIN_OUT" ]; then
  :
else
  # No network / no clean-css: ship the flattened file uncompressed. Correct,
  # just larger — the host's gzip or brotli is the real lever anyway.
  cp "$OUT" "$MIN_OUT"
  echo "note: clean-css unavailable, minified file is a copy" >&2
fi

raw=$(stat -c%s "$OUT"); min=$(stat -c%s "$MIN_OUT")
printf 'sheets : %d files, %s bytes raw\n' "${#SHEETS[@]}" "$TOTAL"
printf 'output : %s (%s bytes)\n' "$OUT" "$raw"
printf 'minified: %s (%s bytes, -%s%%)\n' "$MIN_OUT" "$min" "$(( (raw - min) * 100 / raw ))"
